version: '3'
services:
#mssql docker
  miniafk-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${LO_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - ${MSSQL_PORT}:1433
    #expose:
    #  - 1433
    networks:
      - miniafk2024
    #volumes:
    #  - sqlserverdata:/var/opt/mssql

  miniafk-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=${CONNECTION_STRING}
      #- ConnectionStrings:DefaultConnection=Server=miniafk-sql,1433;Database=miniafk;User=sa;Password=ASDqwe123!;ConnectRetryCount=0; TrustServerCertificate=True
      #- ConnectionStrings:DefaultConnection=${LO_CONNECTION}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - miniafk2024
    links:
      - miniafk-sql
    depends_on:
      - miniafk-sql

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_CREDENTIALS}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_CREDENTIALS}
    networks:
      - miniafk2024
      
networks:
  miniafk2024:
    driver: bridge  
