version: '3'
services:
#mssql docker
  miniafk-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!321ewqDSA
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - miniafk2024

  miniafk-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=miniafk-sql,1433;Database=miniafk;User=sa;Password=!321ewqDSA;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7181:7181
    networks:
      - miniafk2024
    links:
      - miniafk-sql
    depends_on:
      - miniafk-sql
      
networks:
  miniafk2024:
    driver: bridge  
